CMPUT301W24T21/ScanNPlan

app/src/main/res/layout/event_page_list.xml
=> Added event page list, Will add themes later

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/project_3/AttendeeActivity.java, app/src/main/java/com/example/project_3/AttendeeFirebase.java, app/src/main/java/com/example/project_3/Event.java, app/src/main/java/com/example/project_3/User.java
Rn we dont have users so it only grabs events
=> Allows you to grab the users events

app/src/main/res/layout/attendee_info.xml, app/src/main/res/layout/attendees_list.xml, app/src/main/res/layout/edit_event.xml
=> Adding xml files

.idea/navEditor.xml, app/src/main/java/com/example/project_3/AdminEventDetailsFragment.java, app/src/main/java/com/example/project_3/BrowseEventsFragment.java, app/src/main/java/com/example/project_3/BrowseProfilesFragment.java, app/src/main/java/com/example/project_3/ListProfileArrayAdapter.java, app/src/main/java/com/example/project_3/MainActivity.java, app/src/main/java/com/example/project_3/ProfileDetailsFragment.java, app/src/main/res/layout/admin_events.xml, app/src/main/res/layout/admin_profiles.xml, app/src/main/res/layout/event_list_content.xml, app/src/main/res/layout/profiles_list_content.xml
added detailsFragment for managing profiles
=> Fixed navigation between admin fragments

app/build.gradle.kts, app/src/main/java/com/example/project_3/AttendeeEditProfileFragment.java, app/src/main/java/com/example/project_3/BrowseProfilesFragment.java, app/src/main/java/com/example/project_3/MainActivity.java, app/src/main/java/com/example/project_3/OrganizerActivity.java, app/src/main/java/com/example/project_3/Profile.java, app/src/main/java/com/example/project_3/ProfileDetailsFragment.java, app/src/main/res/layout/event_list_content.xml
updated some admin layouts and fixed the constructors
=> Fixed some constructor issues and buttons on admin layouts

app/src/main/java/com/example/project_3/AttendeeListActivity.java, app/src/main/res/layout/activity_event_details.xml
Added the attendees list activity to be implemented later and updated the xml to have an edit button
=> Adding an activity and modifying xml

app/src/main/java/com/example/project_3/BrowseProfilesFragment.java, app/src/main/java/com/example/project_3/MainActivity.java, app/src/main/java/com/example/project_3/ProfileDetailsFragment.java
deletion function works. I manually did profile.setID (doc.getID()) but that shouldnt be an issue anyway since thats what it usually is anyway.
=> added deletion function to the profile fragment

app/src/main/java/com/example/project_3/AttendeeActivity.java, app/src/main/java/com/example/project_3/MainActivity.java
Do not merge right away, need to test
=> Fixed threading issue?

app/src/main/java/com/example/project_3/AdminActivity.java, app/src/main/java/com/example/project_3/BrowseEventsFragment.java, app/src/main/java/com/example/project_3/BrowseImagesFragment.java, app/src/main/java/com/example/project_3/BrowseProfilesFragment.java, app/src/main/java/com/example/project_3/GridImagesArrayAdapter.java, app/src/main/java/com/example/project_3/ListEventArrayAdapter.java, app/src/main/java/com/example/project_3/ListProfileArrayAdapter.java, app/src/main/java/com/example/project_3/ProfileDetailsFragment.java
=> Paul comments

.idea/workspace.xml, app/src/main/AndroidManifest.xml, app/src/main/java/com/example/project_3/Event.java, app/src/main/java/com/example/project_3/EventDetailsActivity.java, app/src/main/java/com/example/project_3/MainActivity.java, app/src/main/java/com/example/project_3/OrganizerActivity.java, app/src/main/res/layout/activity_event_details.xml
=> Kirill's new again

.idea/workspace.xml, app/build.gradle.kts, app/src/main/AndroidManifest.xml, app/src/main/java/com/example/project_3/EventDetailsActivity.java, app/src/main/java/com/example/project_3/EventMapFragment.java, app/src/main/java/com/example/project_3/OrganizerListActivity.java, app/src/main/res/layout/attendee_event_list_content.xml, app/src/main/res/layout/attendees_list.xml, app/src/main/res/layout/map_fragment.xml
currently the attendee1 button is being used as a test button for the map
=> Added MapFragment and fixed some minor layout errors. (current map is empty)

.idea/workspace.xml, app/build.gradle.kts, app/src/main/AndroidManifest.xml, app/src/main/java/com/example/project_3/EventDetailsActivity.java, app/src/main/java/com/example/project_3/EventMapFragment.java, app/src/main/java/com/example/project_3/OrganizerListActivity.java, app/src/main/res/layout/attendees_list.xml
Error checking needs to be done for the events to make sure that checked_in exists for all the docs. (Try Aiden's Party that one works)
=> Added map functionality 

app/src/main/java/com/example/project_3/AttendeeNewEventDetailsFragment.java, app/src/main/java/com/example/project_3/MainActivity.java, app/src/main/java/com/example/project_3/QRScan.java, app/src/main/res/layout/scan_event.xml
=> added ability to scan promo qr and show an event sign up page, and sign up for an event through it. Merged Kirill's and my mainactivity code.

app/src/main/java/com/example/project_3/BrowseEventImagesFragment.java, app/src/main/java/com/example/project_3/BrowseEventsFragment.java, app/src/main/java/com/example/project_3/BrowseProfileImagesFragment.java, app/src/main/java/com/example/project_3/GridEventImagesArrayAdapter.java, app/src/main/java/com/example/project_3/GridProfileImagesArrayAdapter.java, app/src/main/res/layout/admin_event_images.xml, app/src/main/res/layout/admin_profile_images.xml, app/src/main/res/layout/event_images_grid_content.xml, app/src/main/res/layout/profile_images_grid_content.xml
Not fully, completed but needed to push to keep better track, since working on so many files at a time, events images needs to be updated to pull images and it is complete. I tested on local to make sure this push does not murder the app. Browse event pictures will be blank
=> Paul new grid split

app/src/main/java/com/example/project_3/AdminActivity.java
okay here we go that was unnecessarily difficult
=> why is this being so difficult

.idea/workspace.xml, app/src/main/res/layout/attendee_homepage.xml, app/src/main/res/layout/profile_settings.xml
=> added announcements button to attendee homepage, updated profile_settings.xml to make editText fields nicer

app/src/main/java/com/example/project_3/BrowseEventImagesFragment.java, app/src/main/res/layout/admin_event_images.xml
able to browse event in a cleaner nicer grid view
=> Paul grid fixes

.idea/workspace.xml, app/src/main/java/com/example/project_3/EventMapFragment.java, app/src/main/java/com/example/project_3/MainActivity.java, app/src/main/java/com/example/project_3/QRScan.java
also reorganized the location stuff in QRScan
=> removed some extra stuff and made location perms request better. 

app/build.gradle.kts, app/src/main/java/com/example/project_3/AttendeeActivity.java, app/src/main/java/com/example/project_3/AttendeeNewEventDetailsFragment.java, app/src/main/java/com/example/project_3/EditEventDetails.java, app/src/main/java/com/example/project_3/NotificationActivity.java
=> Organizer anouncements now show a notification and are added to the event's respective announcement field

app/src/main/java/com/example/project_3/EventMapFragment.java, app/src/main/java/com/example/project_3/MainActivity.java, app/src/main/java/com/example/project_3/QRScan.java
and moving permissions to main activity since there is some serious lag
=> error handling 

app/src/main/java/com/example/project_3/MainActivity.java, app/src/main/java/com/example/project_3/NotificationActivity.java, app/src/main/java/com/example/project_3/ProfileDetailsFragment.java, app/src/main/java/com/example/project_3/QRScan.java, app/src/main/java/com/example/project_3/User.java
=> Javadocs complete, Android Studio 10/10

app/src/main/java/com/example/project_3/EventDetailsActivity.java, app/src/main/java/com/example/project_3/NotificationActivity.java, app/src/main/java/com/example/project_3/OrganizerActivity.java, app/src/main/res/drawable/gradient_horizontal1.xml, app/src/main/res/layout/event_list_content.xml, app/src/main/res/layout/organizer_events.xml, app/src/main/res/layout/profiles_list_content.xml
=> Final branch will kms
